import pathlib
import re
from typing import *


# =====================================================================================================================
SEPARATOR_PATTERN = r'(\**\n+)*## USAGE EXAMPLES'
STARS_COUNT = 80
LINE_EXAMPLES_START: str = f"\n\n" + "*"*STARS_COUNT + f"\n## USAGE EXAMPLES (autogenerated)\n"
LINE_FILE_HEADER: str = "```python\n"
LINE_FILE_FOOTER: str = "```\n"
LINE_EXAMPLES_FINISH: str = "*"*STARS_COUNT + f"\n"

# =====================================================================================================================
file_readme = pathlib.Path("README.md")
file_readme_text: str = file_readme.read_text().strip()
file_readme_splited = re.split(pattern=SEPARATOR_PATTERN, string=file_readme_text, maxsplit=1)
if len(file_readme_splited) > 1:
    file_readme.write_text(file_readme_splited[0])


# =====================================================================================================================
dirpath = pathlib.Path("examples")
files = [item for item in dirpath.iterdir() if item.is_file()]

# NOTE: don't skip none-python files! it could be as part of examples! just name it in appropriate way!

with file_readme.open("a") as file_readme_append:
    file_readme_append.write(LINE_EXAMPLES_START)
    for index, file in enumerate(files, start=1):
        file_readme_append.write(f"\n### {index}. {file.name}\n")

        file_readme_append.write(LINE_FILE_HEADER)
        file_readme_append.write(f"{file.read_text().strip()}\n")
        file_readme_append.write(LINE_FILE_FOOTER)
    file_readme_append.write(LINE_EXAMPLES_FINISH)


# =====================================================================================================================
